### ISSUE TITLE
Expand functionallity of UnitTestLibrary (3)

### ISSUE THREAD

**Issue by alexejFroebel** [OpusCapita/pim-integrations-expression-unit-test#9]
- [x] built in some features like uomId (additional master data)
- [x] think about using eval => get rid of separate "eval" call
- [x] unpublish it from NPM, adjust documentation to explain installation directly from github
- [x] Update `product enrichment` to use the new version

**Comment by alexejFroebel** [comment]
PR for enrichment repo: https://github.com/OpusCapita/pim-integrations-product-enrichment/pull/4

**Comment by alexejFroebel** [comment]
PR: #10

**Comment by pflenker** [comment]
only a minor QA finding - I added it to the pull request. after the change, no additional QA is needed.

**Comment by alexejFroebel** [comment]
So this can be merged?

**Comment by pflenker** [comment]
Yes

**Comment by alexejFroebel** [comment]
Finished
